#!/bin/bash

#SBATCH --job-name="TSR1"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH --no-requeue

/oasis/scratch/comet/h7ris/temp_project/NumericalValidations/BaselineCase/TSR1/Allrun > /dev/null